# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Maksim Zhirnov - Growth Marketing Expert with exceptional track record in product scaling, industry recognition, and proven expertise in marketing technology innovation. Independent consultant and industry advisor.'
    keywords: 'growth marketing, product strategy, user acquisition, data-driven marketing, growth hacking, conversion optimization, marketing consultant'
    twitter: ''
  analytics:
    google_tag_manager: 'GTM-PCQKVF3'
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true
    logo:
        text: "Maksim Zhirnov"
        # filename: "logo.png"

# Site footer
footer:
  copyright:
    notice: '© {year} Maksim Zhirnov.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/HugoBlox/hugo-blox-builder/'
    content_dir: starters/blog/content
    branch: main